package:
  name: genepender
  version: "v2.6"

source:
  url: https://github.com/BioTools-Tek/genepender/archive/master.zip
  md5: 38878127f7a8da6d788eb7111132f963
   

build:
  number: 0
  #skip: True # [osx]

requirements:
  build:
    - gcc
    - zlib {{CONDA_ZLIB}}*
    - qt

  run:
    - libgcc
    - qt


test:
  commands:
    - genepender 2>&1 | grep "OPTIONS:"

about:
  home: https://github.com/BioTools-Tek/genepender
  license: GPLv3
  summary: Annotates overlapping BED-defined regions to variants in a VCF file. Used primarily for providing a gene/exon context to variants (see:bedtarget).
