package:
  name: swiftlink
  version: 1.0

source:
  fn: swiftlink-2017-10-11.tar.gz
  url: https://github.com/BioTools-Tek/packages/blob/master/swiftlink/swiftlink-2017-10-11.tar.gz?raw=true
  md5: 48fd5b3a66386304d0d726bf5c03de17
    
build:
  number: 0

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]

  run:
    - libgcc
    - gsl
    - openblas

test:
  commands:
    - swift -h

about:
  home: https://github.com/ajm/swiftlink
  license: GPLv3
  summary: A multipoint parametric linkage analysis tool for large consanguineous pedigrees and is primarily targeted at pedigrees that cannot be analysed by a Lander-Green algorithm based program, i.e. many markers, but larger pedigrees.
